name: Build Dist

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    paths:
      - ".release-please-manifest.json"

permissions:
  contents: write

jobs:
  build-dist:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'autorelease: pending')
    steps:
      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Commit dist changes
        run: |
          git config user.name benhodgson87-actions-bot[bot]
          git config user.email 238876957+benhodgson87-actions-bot[bot]@users.noreply.github.com
          git add -f dist/
          git commit -m "chore: build dist" || true
          git push
