name: Lint PR Title

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint PR Title
        uses: benhodgson87/conventional-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
